title: Jayant Blogs
description: Resume & Blog
url: https://jporwal05.github.io
baseurl: ""

remote_theme: pages-themes/midnight@v0.2.0

collections:
  posts:
    output: true
    permalink: /blog/:slug/
    remote_theme: pages-themes/midnight@v0.2.0

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      published: true

plugins:
  - jekyll-feed